### ISSUE TITLE
Is there a way to use optgroups?

### ISSUE THREAD

**Issue by rzmz** [rubenv/angular-select2#16]
I need to group items in my selects. How can this be done?

**Comment by mlvn23** [comment]
Look at the Example of Hierarchical Data section in Select2 documentation. You need to use children. Unfortunately, it looks like this directive doesn't handle that (select2 will display and return the data, but something in the optionItems lookup didn't take care of the children case). Trying to hack it right now.

**Comment by mlvn23** [comment]
It looks there's two options: a) recursively collect the IDs if an entry has children (select2 apparent supports multi-levels not just 2), or b) skip the optionItems altogether. I got the first option to work but not the second. Do we really need the indirection provided by optionItems? If it's just a key data type conversion thing, maybe we could just drop it altogether. It seems very inefficient to recursively do this ID collection for every query.

**Comment by rubenv** [comment]
> If it's just a key data type conversion thing, maybe we could just drop it altogether.

It's exactly that, but it's very important for where it's currently being used. Correctly setting integer keys on the model when integer keys were passed in matters a lot.

We can't drop that.

**Comment by rzmz** [comment]
Hi, I got it working in some degree (using children):
https://github.com/rzmz/angular-select2/commit/25ad952835c8d1ef7e89b353399e0b835660d98f
Only thing that bothers me is that clicking on an opt group does not select group but closes the dropdown. Should leave it as is and not respond to user click in any way (if there is no id provided with the element)
I can create a pull request if you think this is something to go with.

**Comment by piernik** [comment]
Any news on this?
