### ISSUE TITLE
Should this work in IE8

### ISSUE THREAD

**Issue by devotox** [rubenv/angular-select2#29]
I kept getting this error 
  Error: [$compile:tplrt] http://errors.angularjs.org/1.2.28/$compile/tplrt?p0=select2&p1=&lt;:section class=ng-scope ng-include="'templates/sign-up/sign-up-form-page-2.html'" ng-if="page == 2"&gt;

**Comment by rubenv** [comment]
That error does not seem to be related to angular-select2 :-)
