### ISSUE TITLE
Controller 'select', required by directive 'ngOptions', can't be found!

### ISSUE THREAD

**Issue by vapits** [rubenv/angular-select2#36]
I have just update my app to latest stable angular version 1.4.8 and i'm getting this Error:

Controller 'select', required by directive 'ngOptions', can't be found!

Within every page that includes the angular-select2 directive.

Any ideas?

**Comment by rubenv** [comment]
Yes, this: https://github.com/rubenv/angular-select2/commit/f9ec6ec75c769482ab6ff68400eba96716cc89ba

Use `s2-options` for select2.

**Comment by vapits** [comment]
@rubenv feels awkward for me now, thx :)

**Comment by rubenv** [comment]
Yeah, I don't like it either, but there's nothing we can do about it :-(

**Comment by rohtashsethi** [comment]
We have to use bs-options instead of ng-options. AngularStrap provide a directive bs-options for TypeAhead.
http://mgcrea.github.io/angular-strap/#typeaheads
